inherit_from: .rubocop_todo.yml

# ハッシュの記法はロケット記法ではなくruby1.9のハッシュ記法を使う
HashSyntax:
  EnforcedStyle: ruby19

# missing top-level class documentation commentというアラートをオフ
Documentation:
  Enabled: false


LineLength:
  Max: 150

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 6.0.3.4
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'app/controllers/api/v1/**/*'