version: '3'
services:
  db:
    image: mysql:8.0.22
    # ports:
    #   - '3306:3306' # dbはwebと繋げるだけで外から繋がないから不要
    volumes:
      - mysql_data:/var/lib/mysql # データの永続化
      # - mysql_data:/usr/local/var/mysql/  # mysqlのデータ格納場所
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
    environment:
      MYSQL_ROOT_PASSWORD: 'coffeeanywhere'

  web:
    build: .  # Dockerfile のあるディレクトリのパスを指定
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bundle exec foreman start # vue使うためにrails sと共にwebpacker用のサーバー立ち上げ
      # - yarn install --check-files
    ports:
      - '3000:3000' # localhostの3000ポートでアクセスできるようにする
      - '3035:3035' # webpacker
    volumes:
      - .:/coffee_anywhere # アプリケーションファイルの同期
    depends_on:
      - db
      - test
    stdin_open: true
    tty: true

  test:
    image: mysql:8.0.22
    # ports:
    #   - '3307:3306' # ローカルPCから接続するために設定
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
    environment:
      MYSQL_ROOT_PASSWORD: 'coffeeanywhere'
      MYSQL_DATABASE: 'coffee_anywhere_test'
      # MYSQL_USER: 'coffee-user'
      # MYSQL_HOST: test
      MYSQL_PASSWORD: 'coffeeanywhere'

volumes:
  mysql_data:
    driver: local