version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
# read more about orbs: https://circleci.com/docs/2.0/using-orbs/
# orbs:
#   ruby: circleci/ruby@1.0 
#   node: circleci/node@2

jobs:
  build: # our first job, named "build"
    docker:
      # - image: cimg/ruby:2.7-node # use a tailored CircleCI docker image.
      - image: circleci/ruby:2.7.1-node 
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment: # 環境変数の設定
          - RAILS_ENV: test
          - DB_PASSWORD: 'coffeeanywhere'
          - DB_USER: 'coffee-user'
          - DB_HOST: 127.0.0.1
        #   - DB_PASSWORD: 'coffeeanywhere'
        #   - DB_USER: 'root'
        #   - DB_HOST: 127.0.0.1

    # steps:
    #   - checkout # pull down our git code.
    #   - ruby/install-deps # use the ruby orb to install dependencies
      # use the node orb to install our packages
      # specifying that we use `yarn` and to cache dependencies with `yarn.lock`
      # learn more: https://circleci.com/docs/2.0/caching/
      # - node/install-packages: 
      #     pkg-manager: yarn
      #     cache-key: "yarn.lock"
      - image: circleci/mysql:8.0.22
        # caching_sha2_password がないというエラー対策
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          # - RAILS_ENV: test
          # - DB_PASSWORD: 'coffeeanywhere'
          # - DB_USER: 'coffee-user'
          # - DB_HOST: 127.0.0.1
          # MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: '%'

    # working_directory: 実行ディレクトリを設定する。デフォルトは ~/project
    working_directory: ~/repo

    # checkout: CI環境上の working_directory の値の場所にGitリポジトリをコピーする。
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: bundle installの結果をrestore
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: yarn install
          command: yarn install --check-files

      - run:
          name: bundle installを実行
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: bundle installの結果をキャッシュ
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # - run:
      #     name: Wait for DB
      #     command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      # Database setup
      - run: mv config/database.ci.yml config/database.yml

      - run:
          name: DB の待機
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Database setup
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Rspec
          command: bundle exec rspec