# test:
#   adapter: mysql2
#   # encoding: utf8m4
#   # charset: utf8
#   # collation: utf8mb4_general_ci
#   pool: 5
#   username: root
#   port: 3306
#   host: 127.0.0.1
#   username: coffee-user
#   database: coffee_anywhere_test


test: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch("MYSQL_USERNAME") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  host: <%= ENV.fetch("MYSQL_HOST") %>
  port: <%= ENV.fetch("MYSQL_PORT") %>
  database: coffee_anywhere_test